CREATE OR REPLACE DATABASE DATAPROJECT_{{environment}};


CREATE SCHEMA IF NOT EXISTS DW;

USE SCHEMA DATAPROJECT_{{environment}}.DW;

CREATE OR REPLACE TABLE EMPLOYMENT_BY_INDUSTRY (
	"Period" VARCHAR(16777216),
	"Year" NUMBER(38,0),
	"Month" NUMBER(38,0),
	"SeriesID" VARCHAR(16777216),
	"Industry_Name" VARCHAR(16777216),
	"Metric_Value" FLOAT,
	"Created_Date" TIMESTAMP_LTZ(0)
);