USE DATABASE DATAPROJECT_{{environment}};

ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_DW_HIERACHIES_L2 RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_DW_HIERACHIES_L2_HOURLY_EARNINGS RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_DW_HIERACHIES_L2_WEEKLY_HOURS RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_DW_HIERACHIES_L4 RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_DW_HIERACHIES_L4_HOURLY_EARNINGS RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_DW_HIERACHIES_L4_WEEKLY_HOURS RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_EVENT RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_HOURLY_EARNINGS_BY_INDUSTRY RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_WEEKLY_HOURS_BY_INDUSTRY RESUME;
ALTER TASK DATAPROJECT_{{environment}}.PUBLIC.LOAD_EMPLOYMENT_BY_INDUSTRY RESUME;
